input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["error-logs"]
    codec => json
    group_id => "logstash-consumer-group"
    auto_offset_reset => "earliest"
    decorate_events => true
  }
}

filter {
  mutate {
    add_field => { "env" => "production" }
  }
  
  if [level] == "error" {
    fingerprint {
      source => ["service", "message"]
      target => "messageHash"
      method => "SHA1"
      key => "faultlens-secret-key"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "error-logs-%{+YYYY.MM.dd}"
    manage_template => true
    template => "/usr/share/logstash/templates/template.json"
    template_name => "error-logs"
    template_overwrite => true
  }
  stdout { codec => rubydebug }
}
